apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-cilist-fe
 namespace: production
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: cilist-fe
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50